#ifndef OBJ_LIBRARY_OBJ_SETTINGS_H
#define OBJ_LIBRARY_OBJ_SETTINGS_H
#define OBJ_LIBRARY_PATH_PROPAGATION


#define OBJ_LIBRARY_LINEAR_TEXTURE_INTERPOLATION


#define OBJ_LIBRARY_TR_0_IS_OPAQUE

#ifdef OBJ_LIBRARY_SHADER_DISPLAY
	#ifndef OBJ_LIBRARY_GLM_INTERACTION
		#error "OBJ_LIBRARY_GLM_INTERACTION requires OBJ_LIBRARY_GLM_INTERACTION"
	#endif
#endif





#endif
